name: ":rocket: Feature request"
about: Suggest an idea for this project
title: Support for [thing]
labels: enhancement
assignees: ''


**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**New or affected parameter(s)/configuration(s)**
A clear and concise description of what you want to happen.

**Potential Terraform configuration**
A clear and concise description of any alternative solutions or features you've considered.

**References**
Add any other context or screenshots about the feature request here.
