name: "🚀 Feature request"
description: I have a suggestion to implement in this module
title: Support for [thing]
labels: enhancement
assignees: []
body:
  - type: markdown
    id: description
    attributes:
      label: Description
      description: Please leave a helpful description of the feature request here.
    validations:
      required: true
  - type: input
    attributes:
      label: New or affected parameter(s)/configuration(s)
      description: Please list the new or affected parameter(s) and/or configuration(s).
      # placeholder: azurerm_XXXXX
  - type: textarea
    id: config
    attributes:
      label: Potential Terraform Configuration
      description: Please provide an example of what the new resource or enhancement could look like in a Terraform config.
      render: hcl
  - type: input
    attributes:
      label: References
      description: Add any other context or screenshots about the feature request here.
      placeholder: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group
