name: "pre-commit"

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  issues: write
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~>1.9.0"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install tflint terraform-docs

      - uses: pre-commit/action@v3.0.1
        id: plan
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.USER_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${{ steps.plan.outputs.stdout }}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
